// Generated by https://quicktype.io

export interface UserInterface {
    id:       string;
    name:     Name;
    points:   number;
    animals:  string[];
    isActive: boolean;
    age:      number;
}

export interface Name {
    given:   string;
    surname: string;
}
